/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.practica.vista;

import com.practica.conexionbd.Conexionbd;
import com.practica.controlador.Paginasbd;
import com.practica.modelTable.ComunicacionPagina;
import com.practica.modelTable.modelTablePaginas;
import com.practica.modelo.Pagina;
import com.practica.utilidades.Utilidades;
import java.awt.Desktop;
import java.net.URI;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author IdeaPad - S340
 */
public class RegistroPaginas extends javax.swing.JFrame implements ComunicacionPagina {

    private GestionPaginas gestionPaginas;
    private Utilidades utilidades;
    private modelTablePaginas modelTablePaginas;
    private Paginasbd controladorPaginas;
    private Pagina paginaEditar;

    /**
     * Creates new form RegistroPaginas
     */
    public RegistroPaginas() {
        controladorPaginas = new Paginasbd();
        utilidades = new Utilidades();
        modelTablePaginas = new modelTablePaginas(controladorPaginas.obtenerPaginas(), this);

        initComponents();
        bloquear();
        gestionPaginas = new GestionPaginas(txtnombrepagina, txtlinkpagina, txtguardadopor, txtrecordatorio, comboboxtipopagina, utilidades, this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombrepagina = new javax.swing.JTextField();
        txtlinkpagina = new javax.swing.JTextField();
        comboboxtipopagina = new javax.swing.JComboBox<>();
        txtguardadopor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtrecordatorio = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        botguardarPagina = new javax.swing.JButton();
        boteditarPagina = new javax.swing.JButton();
        botlimpiarCampos = new javax.swing.JButton();
        botnuevapagina = new javax.swing.JButton();
        botcancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPaginas = new javax.swing.JTable();
        boteliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        combobuscarPaginas = new javax.swing.JComboBox<>();
        txtbuscarpaginas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtenlace = new javax.swing.JTextField();
        botabrirenlace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Paginas Web");

        jTabbedPane5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo de Registro"));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel2.setText("NOMBRE DE LA PAGINA");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel3.setText("LINK DE LA PAGINA");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel4.setText("TIPO DE PAGINA");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel5.setText("GUARDADO POR");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel6.setText("RECORDATORIO");

        txtlinkpagina.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlinkpaginaFocusLost(evt);
            }
        });

        comboboxtipopagina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo de pagina", "Tienda Online", "BLog", "Foro", "Red Social", "Educacion", "Noticias", "Buscadores", "Multimedia", "Juegos", "Streaming", "Otros" }));

        txtrecordatorio.setColumns(20);
        txtrecordatorio.setLineWrap(true);
        txtrecordatorio.setRows(5);
        txtrecordatorio.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtrecordatorio);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombrepagina)
                    .addComponent(txtlinkpagina)
                    .addComponent(txtguardadopor)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboboxtipopagina, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(131, 131, 131))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombrepagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtlinkpagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboboxtipopagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtguardadopor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Paginas");

        botguardarPagina.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        botguardarPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/practica/imagenes/diskette.png"))); // NOI18N
        botguardarPagina.setText("Guardar");
        botguardarPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botguardarPaginaActionPerformed(evt);
            }
        });

        boteditarPagina.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        boteditarPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/practica/imagenes/edit.png"))); // NOI18N
        boteditarPagina.setText("Editar");
        boteditarPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boteditarPaginaActionPerformed(evt);
            }
        });

        botlimpiarCampos.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        botlimpiarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/practica/imagenes/escoba.png"))); // NOI18N
        botlimpiarCampos.setText("Limpiar");
        botlimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botlimpiarCamposActionPerformed(evt);
            }
        });

        botnuevapagina.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        botnuevapagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/practica/imagenes/plus.png"))); // NOI18N
        botnuevapagina.setText("Nuevo");
        botnuevapagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botnuevapaginaActionPerformed(evt);
            }
        });

        botcancelar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        botcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/practica/imagenes/cancelar.png"))); // NOI18N
        botcancelar.setText("Cancelar");
        botcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(botnuevapagina)
                .addGap(39, 39, 39)
                .addComponent(botguardarPagina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boteditarPagina)
                .addGap(38, 38, 38)
                .addComponent(botcancelar)
                .addGap(36, 36, 36)
                .addComponent(botlimpiarCampos)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botnuevapagina)
                    .addComponent(botguardarPagina)
                    .addComponent(boteditarPagina)
                    .addComponent(botlimpiarCampos)
                    .addComponent(botcancelar))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Registro", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaPaginas.setModel(modelTablePaginas);
        jScrollPane2.setViewportView(tablaPaginas);

        boteliminar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        boteliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/practica/imagenes/delete.png"))); // NOI18N
        boteliminar.setText("Eliminar");
        boteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boteliminarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Buscar por:");

        combobuscarPaginas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un metodo para buscar", "Nombre", "Tipo de Pagina", "Guardado por" }));

        txtbuscarpaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarpaginasKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Lista de Paginas Guardadas");

        botabrirenlace.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        botabrirenlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/practica/imagenes/icons8-enlace-externo-24.png"))); // NOI18N
        botabrirenlace.setText("Abrir Enlace");
        botabrirenlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botabrirenlaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtenlace, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botabrirenlace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(boteliminar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobuscarPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscarpaginas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobuscarPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscarpaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boteliminar)
                    .addComponent(txtenlace, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botabrirenlace))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Paginas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void actualizarTabla() {
        List<Pagina> tablaActualizada = controladorPaginas.obtenerPaginas();

        modelTablePaginas.setPaginas(tablaActualizada);
        modelTablePaginas.fireTableDataChanged();
    }

    void bloquear() {
        txtnombrepagina.setEditable(false);
        txtlinkpagina.setEditable(false);
        txtguardadopor.setEditable(false);
        txtrecordatorio.setEditable(false);
        comboboxtipopagina.setEditable(false);
        botguardarPagina.setEnabled(false);
        boteditarPagina.setEnabled(true);
    }

    void desbloquear() {
        txtnombrepagina.setEditable(true);
        txtlinkpagina.setEditable(true);
        txtguardadopor.setEditable(true);
        txtrecordatorio.setEditable(true);
        comboboxtipopagina.setEditable(true);
        botguardarPagina.setEnabled(true);
        boteditarPagina.setEnabled(false);
    }
     void desbloquearEditar() {
        txtnombrepagina.setEditable(true);
        txtlinkpagina.setEditable(true);
        txtguardadopor.setEditable(true);
        txtrecordatorio.setEditable(true);
        comboboxtipopagina.setEditable(true);
        botguardarPagina.setEnabled(false);
        boteditarPagina.setEnabled(true);
    }
    private void botguardarPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botguardarPaginaActionPerformed

            Pagina paginaGuardar = gestionPaginas.guardarEditar(false);
            if (paginaGuardar != null) {
                if (controladorPaginas.registrarPagina(paginaGuardar)) {
                    JOptionPane.showMessageDialog(rootPane, "Pagina registrada correctamente");
                    gestionPaginas.limpiarcampos();
                    actualizarTabla();
                    bloquear();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se puede guardar la pagina");
                }
            }
    }//GEN-LAST:event_botguardarPaginaActionPerformed

    private void boteditarPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boteditarPaginaActionPerformed

        if (paginaEditar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una pagina seleccionada para editar");
            return;
        }
        Pagina paginaGuardar = gestionPaginas.guardarEditar(true);
        if (paginaGuardar != null) {
            paginaGuardar.setIdpagina(paginaEditar.getIdpagina());
            if (controladorPaginas.editarPagina(paginaGuardar)) {
                JOptionPane.showMessageDialog(rootPane, "Pagina editada correctamente");
                gestionPaginas.limpiarcampos();
                actualizarTabla();
                bloquear();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la pagina");
            }

        }


    }//GEN-LAST:event_boteditarPaginaActionPerformed

    private void botlimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botlimpiarCamposActionPerformed
        gestionPaginas.limpiarcampos();
        tablaPaginas.clearSelection();
        
        
    }//GEN-LAST:event_botlimpiarCamposActionPerformed

    private void boteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boteliminarActionPerformed
        if (paginaEditar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una pagina seleccionada para editar");
            return;
        }
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar la pagina de la lista", "Eliminar Pagina", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (paginaEditar != null) {
                paginaEditar.setIdpagina(paginaEditar.getIdpagina());
                if (controladorPaginas.eliminarpagina(paginaEditar)) {
                    JOptionPane.showMessageDialog(rootPane, "Pagina eliminada correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    gestionPaginas.limpiarcampos();
                    actualizarTabla();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se puede eliminar la pagina");
                }
            }
        }
    }//GEN-LAST:event_boteliminarActionPerformed

    private void botabrirenlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botabrirenlaceActionPerformed
        try {
            Desktop.getDesktop().browse(new URI(txtenlace.getText()));
            JOptionPane.showMessageDialog(rootPane, "Abriendo enlace");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "No se puede abrir el enlace");

        }
    }//GEN-LAST:event_botabrirenlaceActionPerformed

    private void txtlinkpaginaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlinkpaginaFocusLost

        if (!utilidades.validarLink(txtlinkpagina.getText())) {
            JOptionPane.showMessageDialog(this, "El link ingresado no es correcto", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtnombrepagina.requestFocus();

        }
    }//GEN-LAST:event_txtlinkpaginaFocusLost

    private void botnuevapaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botnuevapaginaActionPerformed
        desbloquear();
    }//GEN-LAST:event_botnuevapaginaActionPerformed

    private void txtbuscarpaginasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarpaginasKeyReleased
        switch (combobuscarPaginas.getSelectedIndex()) {
            case 1:
                modelTablePaginas.setPaginas(controladorPaginas.buscarNombre(txtbuscarpaginas.getText()));
                modelTablePaginas.fireTableDataChanged();
                break;
            case 2:
                modelTablePaginas.setPaginas(controladorPaginas.buscarTipoPagina(txtbuscarpaginas.getText()));
                modelTablePaginas.fireTableDataChanged();
                break;
            case 3:
                modelTablePaginas.setPaginas(controladorPaginas.buscarGuardadoPor(txtbuscarpaginas.getText()));
                modelTablePaginas.fireTableDataChanged();
                break;

        }
    }//GEN-LAST:event_txtbuscarpaginasKeyReleased

    private void botcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botcancelarActionPerformed
        bloquear();
    }//GEN-LAST:event_botcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Conexionbd co = new Conexionbd();
        co.getConexion();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPaginas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPaginas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPaginas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPaginas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPaginas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botabrirenlace;
    private javax.swing.JButton botcancelar;
    private javax.swing.JButton boteditarPagina;
    private javax.swing.JButton boteliminar;
    private javax.swing.JButton botguardarPagina;
    private javax.swing.JButton botlimpiarCampos;
    private javax.swing.JButton botnuevapagina;
    private javax.swing.JComboBox<String> comboboxtipopagina;
    private javax.swing.JComboBox<String> combobuscarPaginas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable tablaPaginas;
    private javax.swing.JTextField txtbuscarpaginas;
    private javax.swing.JTextField txtenlace;
    private javax.swing.JTextField txtguardadopor;
    private javax.swing.JTextField txtlinkpagina;
    private javax.swing.JTextField txtnombrepagina;
    private javax.swing.JTextArea txtrecordatorio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickPaginas(Pagina p) {
        desbloquearEditar();
        txtnombrepagina.setText(p.getNombre_pagina());
        txtlinkpagina.setText(p.getLink_pagina());
        comboboxtipopagina.setSelectedItem(p.getTipo_pagina());
        txtguardadopor.setText(p.getGuardado_por());
        txtrecordatorio.setText(p.getRecordatorio());
        txtenlace.setText(p.getLink_pagina());

        paginaEditar = p;
        

    }
}
